package com.javarush.games.minesweeper.graphics;

/**
 * A list of all available graphics (tiles, sprites and pictures) to use as words in the code
 */

public enum Bitmap {
    NONE,

    /* TILES */
    TILE_OPENED, TILE_CLOSED, TILE_DESTROYED,

    /* SPRITES */
    BOARD_NONE,
    BOARD_1,
    BOARD_2,
    BOARD_3,
    BOARD_4,
    BOARD_5,
    BOARD_6,
    BOARD_7,
    BOARD_8,
    BOARD_9,
    BOARD_0,
    BOARD_FLAG,
    BOARD_MINE,
    BOARD_ACTIVE_FRAME,

    /* BIG PICTURES */
    PICTURE_LOGO, PICTURE_FACE_HAPPY, PICTURE_FACE_SAD,

    /* MENU */
    MENU_ARROW, MENU_DIFFICULTY_BAR, MENU_SWITCH, MENU_SWITCH_RAIL, MENU_BUTTON, CUP,

    /* SHOP */
    ITEM_FRAME, ITEM_SHIELD, ITEM_SCANNER, ITEM_FLAG, ITEM_SHOVEL, ITEM_DICE, ITEM_BOMB, SHOP_COIN,
    DICE_1, DICE_2, DICE_3, DICE_4, DICE_5, DICE_6,

    /* WINDOWS */
    WINDOW_MENU, WINDOW_SHOP, WINDOW_VICTORY, WINDOW_GAME_OVER, WINDOW_SHOP_PANEL, WINDOW_ITEM_HELP,

    /* BUTTONS */
    BUTTON_OK, BUTTON_CLOSE, BUTTON_MENU,

    /* ALPHABET */
    RUSSIAN_LETTER_A,
    RUSSIAN_LETTER_B,
    RUSSIAN_LETTER_V,
    RUSSIAN_LETTER_G,
    RUSSIAN_LETTER_D,
    RUSSIAN_LETTER_YE,
    RUSSIAN_LETTER_YO,
    RUSSIAN_LETTER_J,
    RUSSIAN_LETTER_Z,
    RUSSIAN_LETTER_I,
    RUSSIAN_LETTER_IKR,
    RUSSIAN_LETTER_K,
    RUSSIAN_LETTER_L,
    RUSSIAN_LETTER_M,
    RUSSIAN_LETTER_N,
    RUSSIAN_LETTER_O,
    RUSSIAN_LETTER_P,
    RUSSIAN_LETTER_R,
    RUSSIAN_LETTER_S,
    RUSSIAN_LETTER_T,
    RUSSIAN_LETTER_U,
    RUSSIAN_LETTER_F,
    RUSSIAN_LETTER_H,
    RUSSIAN_LETTER_C,
    RUSSIAN_LETTER_CH,
    RUSSIAN_LETTER_SHA,
    RUSSIAN_LETTER_SCHA,
    RUSSIAN_LETTER_SOFT,
    RUSSIAN_LETTER_Y,
    RUSSIAN_LETTER_HARD,
    RUSSIAN_LETTER_E,
    RUSSIAN_LETTER_YU,
    RUSSIAN_LETTER_YA,
    DIGIT_0,
    DIGIT_1,
    DIGIT_2,
    DIGIT_3,
    DIGIT_4,
    DIGIT_5,
    DIGIT_6,
    DIGIT_7,
    DIGIT_8,
    DIGIT_9,
    ENGLISH_LETTER_D,
    ENGLISH_LETTER_F,
    ENGLISH_LETTER_G,
    ENGLISH_LETTER_I,
    ENGLISH_LETTER_J,
    ENGLISH_LETTER_L,
    ENGLISH_LETTER_N,
    ENGLISH_LETTER_Q,
    ENGLISH_LETTER_R,
    ENGLISH_LETTER_S,
    ENGLISH_LETTER_U,
    ENGLISH_LETTER_V,
    ENGLISH_LETTER_W,
    ENGLISH_LETTER_Y,
    ENGLISH_LETTER_Z,
    SYMBOL_COMMA,
    SYMBOL_DOT,
    SYMBOL_COLON,
    SYMBOL_EXCLAMATION,
    SYMBOL_QUESTION,
    SYMBOL_SPACE,
    SYMBOL_DASH,
    SYMBOL_EQUALS,
    SYMBOL_ASTERISK,
    SYMBOL_NEWLINE,
}
