package com.javarush.games.minesweeper.graphics;

/**
 * A list of all available graphics (tiles, sprites and pictures) to use as words in the code
 */

public enum Bitmap {
    NONE,

    /* TILES */
    CELL_OPENED, CELL_CLOSED, CELL_DESTROYED,

    /* SPRITES */
    BOARD_NONE,
    BOARD_1,
    BOARD_2,
    BOARD_3,
    BOARD_4,
    BOARD_5,
    BOARD_6,
    BOARD_7,
    BOARD_8,
    BOARD_9,
    BOARD_0,
    BOARD_FLAG,
    BOARD_MINE,
    BOARD_ACTIVE_FRAME,

    /* BIG PICTURES */
    PICTURE_LOGO, FACE_HAPPY, FACE_SAD,

    /* MENU */
    MENU_ARROW, MENU_DIFFICULTY_BAR, MENU_SWITCH, MENU_SWITCH_RAIL, MENU_BUTTON, CUP,

    /* SHOP */
    ITEM_FRAME, ITEM_FRAME_PRESSED, ITEM_SHIELD, ITEM_SCANNER, ITEM_FLAG, ITEM_SHOVEL, ITEM_DICE, ITEM_BOMB, BOARD_COIN,
    DICE_1, DICE_2, DICE_3, DICE_4, DICE_5, DICE_6,

    /* WINDOWS */
    WINDOW_MENU, WINDOW_SHOP, WINDOW_VICTORY, WINDOW_GAME_OVER, WINDOW_SHOP_PANEL, WINDOW_ITEM_HELP,

    /* BUTTONS */
    BUTTON_OK, BUTTON_CLOSE,

    /* ALPHABET */
    RU_LETTER_A,
    RU_LETTER_B,
    RU_LETTER_V,
    RU_LETTER_G,
    RU_LETTER_D,
    RU_LETTER_YE,
    RU_LETTER_YO,
    RU_LETTER_J,
    RU_LETTER_Z,
    RU_LETTER_I,
    RU_LETTER_IKR,
    RU_LETTER_K,
    RU_LETTER_L,
    RU_LETTER_M,
    RU_LETTER_N,
    RU_LETTER_O,
    RU_LETTER_P,
    RU_LETTER_R,
    RU_LETTER_S,
    RU_LETTER_T,
    RU_LETTER_U,
    RU_LETTER_F,
    RU_LETTER_H,
    RU_LETTER_C,
    RU_LETTER_CH,
    RU_LETTER_SHA,
    RU_LETTER_SCHA,
    RU_LETTER_SOFT,
    RU_LETTER_Y,
    RU_LETTER_HARD,
    RU_LETTER_E,
    RU_LETTER_YU,
    RU_LETTER_YA,
    DIGIT_0,
    DIGIT_1,
    DIGIT_2,
    DIGIT_3,
    DIGIT_4,
    DIGIT_5,
    DIGIT_6,
    DIGIT_7,
    DIGIT_8,
    DIGIT_9,
    EN_LETTER_D,
    EN_LETTER_F,
    EN_LETTER_G,
    EN_LETTER_I,
    EN_LETTER_J,
    EN_LETTER_L,
    EN_LETTER_N,
    EN_LETTER_Q,
    EN_LETTER_R,
    EN_LETTER_S,
    EN_LETTER_U,
    EN_LETTER_V,
    EN_LETTER_W,
    EN_LETTER_X,
    EN_LETTER_Y,
    EN_LETTER_Z,
    SYMBOL_COMMA,
    SYMBOL_DOT,
    SYMBOL_COLON,
    SYMBOL_EXCLAMATION,
    SYMBOL_QUESTION,
    SYMBOL_SPACE,
    SYMBOL_DASH,
    SYMBOL_EQUALS,
    SYMBOL_ASTERISK,
    SYMBOL_NEWLINE,
    SYMBOL_SLASH
}
